version: "3.7"
services:
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
      - "5005:5005"
    networks:
      - spring-boot-network
networks:
  spring-boot-network:
    driver: bridge