server:
  port: 9090

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          custom-client:
            provider: custom-provider
            client-id: user
            client-secret: secret
            authorization-grant-type: password
            scope: user
        provider:
          custom-provider:
            token-uri: http://authorizationserver:8081/oauth/token
            authorization-uri: http://authorizationserver:8081/oauth/authorize
messages:
  base-uri: http://resourceserver:8080/
