version: "3.7"
services:
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - m2-repo:/root/.m2/repository
    networks:
      - spring-boot-network
networks:
  spring-boot-network:
    driver: bridge
volumes:
  m2-repo: